2018-08-11 10:49:04 - error al cargar configuracion
java.io.FileNotFoundException: config.properties (El sistema no puede encontrar el archivo especificado)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_152]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_152]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_152]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_152]
	at dario.java.std.jdbc.biblioteca.Configuracion.<init>(Configuracion.java:31) [classes/:na]
	at dario.java.std.jdbc.biblioteca.Configuracion.getInstancia(Configuracion.java:20) [classes/:na]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.<init>(AdministradorDeConexiones.java:21) [classes/:na]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.getInstancia(AdministradorDeConexiones.java:35) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.obtenerConexion(SoporteDao.java:132) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.grabar(SoporteDao.java:22) [classes/:na]
	at dario.java.std.jdbc.biblioteca.Biblioteca.main(Biblioteca.java:17) [classes/:na]
2018-08-11 10:50:40 - error al cargar configuracion
java.io.FileNotFoundException: config.properties (El sistema no puede encontrar el archivo especificado)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_152]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_152]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_152]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_152]
	at dario.java.std.jdbc.biblioteca.Configuracion.<init>(Configuracion.java:31) [classes/:na]
	at dario.java.std.jdbc.biblioteca.Configuracion.getInstancia(Configuracion.java:20) [classes/:na]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.<init>(AdministradorDeConexiones.java:21) [classes/:na]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.getInstancia(AdministradorDeConexiones.java:35) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.obtenerConexion(SoporteDao.java:132) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.grabar(SoporteDao.java:22) [classes/:na]
	at dario.java.std.jdbc.biblioteca.Biblioteca.main(Biblioteca.java:17) [classes/:na]
2018-08-11 11:58:50 - Error conectandose a la bd
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user ''@'localhost' to database 'biblioteca'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_152]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_152]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_152]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_152]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_152]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_152]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.<init>(AdministradorDeConexiones.java:25) [classes/:na]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.getInstancia(AdministradorDeConexiones.java:35) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.obtenerConexion(SoporteDao.java:132) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.grabar(SoporteDao.java:22) [classes/:na]
	at dario.java.std.jdbc.biblioteca.Biblioteca.main(Biblioteca.java:13) [classes/:na]
2018-08-11 12:33:50 - Error conectandose a la bd
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user ''@'localhost' to database 'biblioteca'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_152]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_152]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_152]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_152]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_152]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_152]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.<init>(AdministradorDeConexiones.java:25) [classes/:na]
	at dario.java.std.jdbc.biblioteca.AdministradorDeConexiones.getInstancia(AdministradorDeConexiones.java:35) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.obtenerConexion(SoporteDao.java:132) [classes/:na]
	at dario.java.std.jdbc.biblioteca.SoporteDao.grabar(SoporteDao.java:22) [classes/:na]
	at dario.java.std.jdbc.biblioteca.Biblioteca.main(Biblioteca.java:17) [classes/:na]
2018-08-11 12:34:05 - Registros modificados: 1
2018-08-11 12:34:05 - guardando cortazar
2018-08-11 12:34:05 - Registros modificados: 1
2018-08-11 12:34:05 - guardando borges
2018-08-11 12:34:05 - Registros modificados: 1
2018-08-11 12:34:05 - guardando planeta
2018-08-11 12:34:05 - Registros modificados: 1
2018-08-11 12:34:05 - guardando rayuela
2018-08-11 12:34:06 - Registros modificados: 1
2018-08-11 12:34:06 - guardando el Aleph
2018-08-11 12:34:06 - Libro{titulo=Rayuela, editorial=Editorial{nombre=planeta, pais=España}, autor=Autor{id=1, nombre=Julio, apellido=Cortazar, nacionalidad=Argentina}}
2018-08-11 12:34:06 - Libro{titulo=El Aleph, editorial=Editorial{nombre=planeta, pais=España}, autor=Autor{id=2, nombre=Jorge Luis, apellido=Borges, nacionalidad=Argentina}}
